project:
  title: "[PROJECT TITLE]"
  execute-dir: project
  output-dir: _output

title: "[PAPER TITLE]"
subtitle: "[SUBTITLE]"
author:
  - name: "[AUTHOR NAME]"
    email: "[EMAIL]"
    affiliation:
      - primary
shortauthor: "[LAST NAME]"
affiliations:
  - id: primary
    name: "[UNIVERSITY]"
    department: "[DEPARTMENT]"
    address: "[CITY, STATE]"
institute: "[UNIVERSITY]"
shortinstitute: "[ABBREV]"
date: last-modified
date-format: long

tbl-cap-location: top

citeproc: true
bibliography: references.bib
csl: https://www.zotero.org/styles/apa

execute:
  echo: false
  warning: false
  message: false
  freeze: auto

pandoc:
  wrap: none

format:
  pdf:
    documentclass: article
    pdf-engine: xelatex
    toc: false
    papersize: letter
    fontsize: 10pt
    geometry: margin=1in
    indent: true
    link-citations: true
    fig-height: 4
    fig-width: 7.5
    fig-pos: "!t"
    keep-tex: false
    number-sections: true

  beamer:
    navigation: horizontal
    keep-tex: true
    incremental: true
    link-citations: true
    section-titles: false
    fonttheme: structurebold
    aspectratio: 169
